# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bonificacion', models.FloatField()),
                ('fechaBonificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fechaInicio', models.DateTimeField()),
                ('estado', models.CharField(max_length=100)),
                ('fechaInactividad', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Igss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Retencion', models.FloatField()),
                ('fechaRetencion', models.DateField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SalarioOrdinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bonificacion',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Empleado'),
        ),
    ]
