# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igss',
            old_name='mes',
            new_name='cuota_igss',
        ),
        migrations.RenameField(
            model_name='salarioordinario',
            old_name='mes',
            new_name='cuota_salario',
        ),
    ]
