# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20161030_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaInactividad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
