# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20161102_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonificacion',
            old_name='Bonificacion',
            new_name='BonificacionCuota',
        ),
    ]
