# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20161102_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaGenerar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Bonificacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Empleado')),
                ('retencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Retencion')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SalarioOrdinario')),
            ],
        ),
    ]
