# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_planillagenerar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retencion',
            old_name='Retencion',
            new_name='RetencionCuota',
        ),
    ]
