# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20161105_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaGenerar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_planilla', models.CharField(max_length=100)),
                ('apellido_planilla', models.CharField(max_length=100)),
                ('fecha_inicio_planilla', models.CharField(max_length=100)),
                ('igss_anio_planilla', models.CharField(max_length=100)),
                ('mes_planilla', models.CharField(max_length=100)),
                ('cuota_salario_planilla', models.CharField(max_length=100)),
                ('bonificacion_planilla', models.CharField(max_length=100, null=True)),
                ('retencion_planilla', models.CharField(max_length=100, null=True)),
                ('sueldoTotal_planilla', models.CharField(max_length=100)),
                ('sueldoLiquido_planilla', models.CharField(max_length=100)),
            ],
        ),
    ]
