# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_planillagenerar'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillagenerar',
            name='igss_cuota',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
